### ISSUE TITLE
Option to either add all config items or not depending on BasedOnStyle

### ISSUE THREAD

**Issue by deft0nes** [Wirena/clang-format-configurator-v2#25]
I really love this tool. However, I would like the generated .clang-format file to only have the items which differ from the style defined in BasedOnStyle and not ALL configuration items. That makes it more readable in my humble opinion. In any ways a great tool!

**Comment by Wirena** [comment]
@deft0nes, you are right about readability, that's how it was originally implemented and is still written in readme file(which i forgot to update), but there was a [bug](https://github.com/Wirena/clang-format-configurator-v2/issues/21) with BraceWrapping option, so I disabled this feature.

In that particular casec the problem was that `BraceWrapping`'s default values depend on `BreakBeforeBraces`, not `BasedOnStyle` option, and I don't know how to automatically extract these default values for each `BreakBeforeBraces` value. Plus, I'm not sure whether it works as expected with other complex options like arrays or structs. I'll enable this feature for simple options with string or enum values, but it'll take a couple of weeks because I don't have access to my personal PC rn
