### ISSUE TITLE
SpacesInLineCommentPrefix Maximum not working

### ISSUE THREAD

**Issue by CappedMonke** [Wirena/clang-format-configurator-v2#54]
See title.

Thanks for the free tool btw!

**Comment by Wirena** [comment]
Can you give more info, like expected behavior and actual behavior? I've tested SpacesInLineCommentPrefix Maximum nested option, and it behaves the same way both on my local PC and in the configurator:

**ReflowComments: false**   -> comments are not edited

**ReflowComments: true**    -> if first line of a comment has more spaces than `Maximum`, then some spaces are erased to match their number to `Maximum`. Spaces in the following comment lines are not edited



```
///        if (b) {                  <- number of spaces will be set to Maximum
///                   return true;   <- not edited
///}                                 <- zero spaces, so affected by Minimum, not Maximum
```
